class Factors:
    """ Main columns"""
    METHOD = "Method"
    PLANT_TYPE = "Plant Type"
    EQUIPMENT = "Equipment"
    EQUIPMENT_TYPE = "Equipment Type"
    SIZING_QUANTITY = "Sizing Quantity"
    UNITS = "Units"
    S_LOWER = "S lower"
    S_UPPER = "S upper"
    A = "a"
    B = "b"
    N = "n"
    INSTALLATION_FACTOR = "Installation Factor"
    MATERIAL_FACTOR = "Material Factor"
    EQUIPMENT_ERECTION_FACTOR = "Equipment Erection Factor"
    PIPING_FACTOR = "Piping Factor"
    INSTRUMENTATION_AND_CONTROL_FACTOR = "Instrumentation and Control Factor"
    ELECTRICAL_FACTOR = "Electrical Factor"
    CIVIL_FACTOR = "Civil Factor"
    STRUCTURES_AND_BUILDINGS_FACTOR = "Structures and Buildings Factor"
    LAGGING_AND_PAINT_FACTOR = "Lagging and Paint Factor"
    ISBL_COST_FACTOR = "ISBL Cost Factor"
    OFFSITES_FACTOR = "Offsites Factor"
    DESIGN_AND_ENGINEERING_FACTOR = "Design and Engineering Factor"
    CONTINGENCY = "Contingency"
    LOCATION_FACTOR = "Location Factor"

class Methods:
    """ Method types """  
    MATERIAL_FACTORS = "material factors"
    HAND = "Hand"
